pipeline {
    agent any

    environment {
        REGISTRY = 'your-openshift-registry-url' // Use single quotes to avoid variable interpolation
        APP_NAME = 'api-gateway'
        PROJECT_NAME = 'your-project-name'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/vr-here-01/vr-here-backend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t ${REGISTRY}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Push Docker Image to OpenShift Registry') {
            steps {
                script {
                    sh '''
                    oc login --token=your-token --server=https://api.your-openshift-cluster:6443
                    docker login -u $(oc whoami) -p $(oc whoami -t) ${REGISTRY}
                    docker push ${REGISTRY}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy to OpenShift') {
            steps {
                script {
                    sh '''
                    oc project ${PROJECT_NAME}
                    oc new-app ${REGISTRY}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG} --name=${APP_NAME} || oc rollout latest ${APP_NAME}
                    oc expose svc/${APP_NAME}
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
