pipeline {
    agent any

    environment {
        REGISTRY = 'image-registry.openshift-image-registry.svc:5000' // Use single quotes to avoid variable interpolation
        APP_NAME = 'api-gateway'
        PROJECT_NAME = 'rupesh-kallepelli-dev'
        IMAGE_TAG = 'latest'
        OPENSHIFT_SERVER = 'https://api.sandbox-m4.g2pi.p1.openshiftapps.com:6443'
        TOKEN = 'sha256~qQERLPLF3gtYXph-UGTcXU7QbwRPutXtIJzr5xl4tck'
    }

    stages {

        stage('Trigger OpenShift Build') {
                steps {
                    dir('api-gateway') {
                        script{
                            try {
                                sh(label: "Login into oc", script: "oc login --token=${TOKEN} --server=${OPENSHIFT_SERVER}")
                                sh(label: "Create imagestream", script: "oc create -f ./helm/imagestream.yaml")
                            } catch (err) {
                                sh(label: "Replace imagestream oc", script: "oc replace -f ./helm/imagestream.yaml")
                            } finally {
                                sh(label: "Start src build", script: "oc start-build ${APP_NAME} --from-dir=helm/ --follow")
                            }
                        }
                    }
                }
        }

        stage('Trigger OpenShift Build') {
            steps {
                dir('api-gateway') {
                    script{
                        try {
                            sh(label: "Login into oc", script: "oc login --token=${TOKEN} --server=${OPENSHIFT_SERVER}")
                            sh(label: "Create buildconfig", script: "oc create -f ./helm/buildconfig.yaml")
                        } catch (err) {
                            sh(label: "Replace buildconfig oc", script: "oc replace -f ./helm/buildconfig.yaml")
                        } finally {
                            sh(label: "Start src build", script: "oc start-build ${APP_NAME} --from-dir=helm/ --follow")
                        }
                    }
                }
            }
        }

        stage('Deploy to OpenShift') {
            steps {
                dir('api-gateway') {
                    sh """
                    oc apply -f ./helm/templates/deployment.yaml
                    oc new-app ${REGISTRY}/${PROJECT_NAME}/${APP_NAME}:${IMAGE_TAG} --name=${APP_NAME} || oc rollout latest ${APP_NAME}
                    oc expose svc/${APP_NAME}
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
