pipeline {
    agent any

    environment {
        REGISTRY = 'your-openshift-registry-url' // Use single quotes to avoid variable interpolation
        APP_NAME = 'api-gateway'
        PROJECT_NAME = 'your-project-name'
        IMAGE_TAG = 'latest'
        OPENSHIFT_SERVER = 'https://api.your-openshift-cluster:6443'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/vr-here-01/vr-here-backend.git'
            }
        }

        stage('Build Maven Project') {
            steps {
                sh './api-gateway/mvnw clean package -DskipTests'
            }
        }

        stage('Trigger OpenShift Build') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'openshift-token', variable: 'TOKEN')]) {
                        // Login to OpenShift
                        sh """
                        oc login --token=\$TOKEN --server=$OPENSHIFT_SERVER
                        oc start-build $APP_NAME --from-dir=api-gateway/ --follow
                        """
                    }
                }
            }
        }

        stage('Deploy to OpenShift') {
            steps {
                script {
                    sh """
                    oc project $PROJECT_NAME
                    oc new-app $REGISTRY/$PROJECT_NAME/$APP_NAME:$IMAGE_TAG --name=$APP_NAME || oc rollout latest $APP_NAME
                    oc expose svc/$APP_NAME
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
