apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-controller
  template:
    metadata:
      labels:
        app: front-controller
    spec:
      containers:
        - name: front-controller
          image: image-registry.openshift-image-registry.svc:5000/rupesh-kallepelli-dev/api-gateway:latest
          env:
            - name: JAVA_MAIN_CLASS
              value: "com.vr.here.api.gateway.FrontControllerApplication"  # Replace with your main class
            - name: JAVA_APP_JAR
              value: "/deployments/front-controller-0.0.1-SNAPSHOT.war"  # Correct the path to deployments
