apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsUser: 1001  # Adjust this based on your user ID needs
        fsGroup: 1001    # This group ID will apply to the volume mount
      containers:
        - name: api-gateway
          image: image-registry.openshift-image-registry.svc:5000/rupesh-kallepelli-dev/api-gateway:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: JAVA_OPTS
              value: "-Djava.util.prefs.userRoot=/var/preferences"
          volumeMounts:
            - name: prefs-volume
              mountPath: /var/preferences  # This is where your app will look for prefs
      volumes:
        - name: prefs-volume
          persistentVolumeClaim:
            claimName: prefs-pvc  # Reference the PVC here
