apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rupesh-kallepelli-dev
  name: api-gateway
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"api-gateway:latest","namespace":"rupesh-kallepelli-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image","paused":"true"}]
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: container
          image: >-
            openjdk@sha256:d2b6af2093e823ba0cdee4bcd45a905afe3fa054d08bde55b1d850515da69a08
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
