apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: api-gateway
  namespace: rupesh-kallepelli-dev
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/vr-here-01/vr-here-backend.git'
    contextDir: api-gateway  # Set the correct context directory
  strategy:
    type: Docker
    dockerStrategy:
      dockerfile: Dockerfile  # The name of your Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: api-gateway:latest  # The name of your ImageStream
