apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: rupesh-kallepelli-dev
  name: vr-backend-build-config
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/vr-here-01/vr-here-backend.git'
    contextDir: /
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'ubi8-openjdk-17:1.17'
