apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: api-gatewayli-dev  # Adjust to your desired namespace
spec:
  tags:
  namespace: rupesh-kallepel
    - name: latest
      from:
        kind: DockerImage
        name: openjdk:11-jdk-slim  # Use the OpenJDK slim image
      importPolicy:
        scheduled: false
